/* Sprite sheet frame mapping.
   - Morphed rangers: "MMPR: The Movie" (Sega Genesis / Mega Drive) sheets
   - Civilians (unmorphed), Putty Patrol and stages: "MMPR: The Movie" (SNES)
   frames.json is generated by tools/slice2.cjs (connected-component slicing).
   Animations are located by frame-size signatures. */
import framesData from "./frames.json";
// All processed sheets are embedded as base64 data URLs (text), generated by
// tools/pack_sheets.cjs — the build never depends on loose binary files.
import sheetsData from "../assets/sheets.json";

export interface Frame {
  x: number;
  y: number;
  w: number;
  h: number;
}
export interface SheetData {
  w: number;
  h: number;
  rows: Frame[][];
  fallback?: boolean; // true when a stand-in sheet replaces a missing original
}

export type CharKey = "red" | "blue" | "black" | "pink" | "yellow" | "white";

export interface AnimSet {
  idle: Frame[];
  walk: Frame[];
  jumpUp: Frame[];
  jumpDown: Frame[];
  punch: Frame[];
  punch2: Frame[];
  punch3: Frame[];
  kick: Frame[];
  kick2: Frame[];
  hurt: Frame[];
  fall: Frame[];
  down: Frame[];
  special: Frame[];
  victory: Frame[];
  morph: Frame[]; // civilians: morpher at chest → arm raised
}

const data = framesData as unknown as Record<string, SheetData>;

export const SHEETS: Record<string, string> = sheetsData as Record<string, string>;

export const RANGER_SHEET: Record<CharKey, string> = {
  red: "gred",
  blue: "gblue",
  black: "gblack",
  pink: "gpink",
  yellow: "gyellow",
  white: "gwhite",
};

export const CIV_SHEET: Record<CharKey, string> = {
  red: "civ_rocky",
  blue: "civ_billy",
  black: "civ_adam",
  pink: "civ_kim",
  yellow: "civ_aisha",
  white: "civ_tommy",
};

const images: Record<string, HTMLImageElement> = {};

export function loadImages(): Promise<void> {
  const jobs = Object.entries(SHEETS).map(
    ([k, url]) =>
      new Promise<void>((res, rej) => {
        const img = new Image();
        img.onload = () => {
          images[k] = img;
          res();
        };
        img.onerror = () => rej(new Error("failed " + url));
        img.src = url;
      }),
  );
  return Promise.all(jobs).then(() => undefined);
}

export function getImage(key: string): HTMLImageElement {
  return images[key];
}

export function sheetSize(key: string): { w: number; h: number } {
  const s = data[key];
  return { w: s.w, h: s.h };
}

/* ---------- signature search helpers ---------- */

function sz(f: Frame, w: number, h: number, tol: number) {
  return Math.abs(f.w - w) <= tol && Math.abs(f.h - h) <= tol;
}

function findSeq(sheet: SheetData, sizes: [number, number][], tol = 2): Frame[] | null {
  for (const row of sheet.rows) {
    for (let i = 0; i + sizes.length <= row.length; i++) {
      let ok = true;
      for (let j = 0; j < sizes.length; j++) {
        if (!sz(row[i + j], sizes[j][0], sizes[j][1], tol)) {
          ok = false;
          break;
        }
      }
      if (ok) return row.slice(i, i + sizes.length);
    }
  }
  return null;
}

function findFrame(sheet: SheetData, w: number, h: number, tol = 2): Frame | null {
  for (const row of sheet.rows) for (const f of row) if (sz(f, w, h, tol)) return f;
  return null;
}

function findWhere(sheet: SheetData, pred: (f: Frame) => boolean): Frame | null {
  for (const row of sheet.rows) for (const f of row) if (pred(f)) return f;
  return null;
}

function rowOf(sheet: SheetData, target: Frame): Frame[] {
  for (const row of sheet.rows) if (row.includes(target)) return row;
  return [target];
}

/* Some sheets have two adjacent poses touching each other; the slicer then
   returns one wide box containing both. These helpers carve it back apart. */
function leftPart(f: Frame, w: number): Frame {
  return { x: f.x, y: f.y, w: Math.min(w, f.w), h: f.h };
}
function rightPart(f: Frame, skip: number): Frame {
  return { x: f.x + skip, y: f.y, w: Math.max(1, f.w - skip), h: f.h };
}
function union(a: Frame, b: Frame): Frame {
  const x = Math.min(a.x, b.x);
  const y = Math.min(a.y, b.y);
  return { x, y, w: Math.max(a.x + a.w, b.x + b.w) - x, h: Math.max(a.y + a.h, b.y + b.h) - y };
}

/* Weapon row of a Genesis ranger sheet. With the slicer's coreMerge option every
   sheet yields the same canonical row, where the weapon is a separate box from
   the body:  [49x67 49x68] [34x64] [52x67 56x68] [32x64]
              └ wind-up ┘  hold   └── swing ──┘  recoil
   Returns [windUp, swing, recoil]. Older slicings (merged/unsplit boxes) are
   handled by the fallbacks below. */
function weaponRow(s: SheetData): Frame[] {
  // canonical split layout
  for (const row of s.rows) {
    if (row.length < 6) continue;
    const [a, b, c, d, e, f] = row;
    if (
      a.w >= 44 &&
      a.w <= 54 &&
      b.w >= 44 &&
      b.w <= 54 &&
      a.h >= 64 &&
      a.h <= 70 &&
      sz(c, 34, 64, 2) &&
      d.w >= 48 &&
      d.w <= 58 &&
      e.w >= 50 &&
      e.w <= 60 &&
      sz(f, 32, 64, 2)
    ) {
      return [union(a, b), union(d, e), f];
    }
  }
  // fallbacks for unsplit / merged layouts
  for (const row of s.rows) {
    if (row.length < 3) continue;
    const first = row[0];
    if (!(first.w >= 88 && first.w <= 102 && first.h >= 66 && first.h <= 72)) continue;
    const recoil = row.find((f) => sz(f, 32, 64, 2));
    if (!recoil) continue;
    let swing: Frame | null =
      row.find((f) => f.w >= 100 && f.w <= 116 && f.h >= 64 && f.h <= 74) || null;
    if (!swing) {
      const merged = row.find((f) => f.w >= 128 && f.w <= 146 && f.h >= 66 && f.h <= 74);
      if (merged) swing = rightPart(merged, 34);
    }
    if (!swing) {
      const i = row.findIndex(
        (f, k) =>
          k + 1 < row.length &&
          f.w >= 48 &&
          f.w <= 58 &&
          f.h >= 64 &&
          f.h <= 70 &&
          row[k + 1].w >= 50 &&
          row[k + 1].w <= 60,
      );
      if (i >= 0) swing = union(row[i], row[i + 1]);
    }
    if (swing) return [first, swing, recoil];
  }
  return [];
}

/* Kick row signature: [52x65 45x66 53x70 56x69 51x69 52x65] — pick the 56x69 apex
   from the row that also holds the 51x69 follow-through (avoids the 56x68 axe box). */
function kickApex(s: SheetData): Frame | null {
  for (const row of s.rows) {
    const apex = row.find((f) => sz(f, 56, 69, 2));
    const follow = row.find((f) => sz(f, 51, 69, 1));
    if (apex && follow) return apex;
  }
  return findFrame(s, 56, 69, 2);
}

/* ---------- Genesis ranger mapping (identical structure per color) ---------- */

function buildGenesisRanger(key: CharKey): AnimSet {
  const s = data[RANGER_SHEET[key]];

  // idle: three ~40x71 frames
  const idle: Frame[] = [];
  for (const row of s.rows) {
    for (const f of row) if (f.w >= 38 && f.w <= 42 && f.h >= 69 && f.h <= 73) idle.push(f);
    if (idle.length >= 3) break;
  }
  if (!idle.length) idle.push(s.rows[0][0]);

  const walk =
    findSeq(s, [
      [41, 70],
      [37, 71],
      [23, 72],
      [39, 70],
      [31, 71],
      [29, 72],
    ]) ||
    findSeq(s, [
      [41, 70],
      [37, 71],
      [23, 72],
      [39, 70],
    ]) ||
    idle;

  const jumpF = findFrame(s, 41, 83, 3);
  const jumpUp = jumpF ? [jumpF] : [idle[0]];
  const landF = findFrame(s, 47, 68, 2);
  const jumpDown = landF ? [landF] : [idle[0]];

  // punch: 47x71 jab → 51x70 → 50x69; punch2: 68x62 straight
  const core = findSeq(s, [
    [51, 70],
    [50, 69],
  ]);
  const jab = findFrame(s, 47, 71, 2);
  const punch = core ? (jab ? [jab, core[0], core[1]] : [core[0], core[1]]) : idle.slice(0, 2);
  const straight = findFrame(s, 68, 62, 2);
  const punch2 = straight ? [punch[0], straight] : punch;

  // kick: row around the 56x69 high kick. On some sheets the two frames before
  // it (45x66 + 53x70) are merged into one ~97x70 box → keep only its right part.
  const kickMid = kickApex(s);
  let kick: Frame[];
  if (kickMid) {
    const row = rowOf(s, kickMid);
    const i = row.indexOf(kickMid);
    kick = row
      .slice(Math.max(0, i - 1), Math.min(row.length, i + 2))
      .map((f) => (f.w >= 90 ? rightPart(f, f.w - 53) : f));
  } else kick = punch;

  const hurtF = findFrame(s, 44, 63, 2);
  const hurt = hurtF ? [hurtF] : [idle[0]];
  // knockdown row: [44x63 hurt] [83x60 fall] [63x68 fall2] [72x37 down] [70x48 get-up]
  // (white ranger: fall + fall2 are merged into one ~147x68 box → split it)
  const downF =
    findFrame(s, 72, 37, 3) ||
    findWhere(s, (f) => f.w >= 60 && f.w <= 82 && f.h >= 16 && f.h <= 40);
  let fallA = findFrame(s, 83, 60, 4);
  let fallB = findFrame(s, 63, 68, 3);
  if (!fallA && downF) {
    const merged = rowOf(s, downF).find((f) => f.w >= 130 && f.w <= 160 && f.h >= 60 && f.h <= 75);
    if (merged) {
      fallA = leftPart(merged, 83);
      fallB = rightPart(merged, 84);
    }
  }
  const down = downF ? [downF] : hurt;
  const fall = [fallA || fallB || hurt[0], down[0]];

  // special: the ranger's weapon swing (wind-up → swing → recoil)
  const wr = weaponRow(s);
  const special: Frame[] = wr.length ? wr : kick;

  const victF = findFrame(s, 38, 80, 2);
  const victory = [victF || idle[0]];

  // combo ender (3rd punch): wind-up jab → fully extended straight (68x62)
  const punchBig = findFrame(s, 68, 62, 2) || punch2[punch2.length - 1] || punch[punch.length - 1];
  const punch3: Frame[] = jab ? [jab, punchBig] : [punchBig];
  // follow-up kick reuses the high kick apex
  const kick2: Frame[] = [kick[Math.min(1, kick.length - 1)]];

  // per-ranger unique weapon attack: see WEAPON_SPECS
  return {
    idle,
    walk,
    jumpUp,
    jumpDown,
    punch,
    punch2,
    punch3,
    kick,
    kick2,
    hurt,
    fall,
    down,
    special, // overwritten by WEAPON_SPECS
    victory,
    morph: victory,
  };
}

/* ---------- SNES civilian mapping (heuristic, per-sheet) ---------- */

function buildCivilian(key: CharKey): AnimSet {
  const s = data[CIV_SHEET[key]];
  const row0 = s.rows[0] || [];
  const row1 = s.rows[1] || row0;

  const idle = row0.filter((f) => f.h >= 55).slice(0, 3);
  if (!idle.length) idle.push(row0[0]);

  const walk = row1.filter((f) => f.h >= 55).slice(0, 6);

  // morph trio (adjacent in one row): wide stance (54-63 x 63-64), standing with the
  // morpher at chest (22-34 x 60-66) and arm raised high (22-34 x 76-86)
  let morphA: Frame | null = null;
  let morphB: Frame | null = null;
  outerMorph: for (const row of s.rows) {
    for (let i = 0; i < row.length; i++) {
      const f = row[i];
      if (!(f.h >= 76 && f.h <= 86 && f.w >= 22 && f.w <= 34)) continue;
      const near = row.slice(Math.max(0, i - 2), i + 3);
      const narrow = near.find((g) => g !== f && g.h >= 60 && g.h <= 66 && g.w >= 22 && g.w <= 34);
      const wide = near.find((g) => g.h >= 60 && g.h <= 66 && g.w >= 50 && g.w <= 66);
      if (narrow && wide) {
        morphA = narrow;
        morphB = f;
        break outerMorph;
      }
    }
  }
  const morph = morphA && morphB ? [morphA, morphB] : [idle[0]];

  // jump: tall narrow frame that is not the morph pose
  const jumpF = findWhere(s, (f) => f !== morphB && f.h >= 66 && f.h <= 90 && f.w <= 40);
  const jumpUp = jumpF ? [jumpF] : [idle[0]];
  const jumpDown = [idle[0]];

  // punch: widest frame h 55-70 & w 49-65 (extended arm), with windups before it
  let punch: Frame[] = idle.slice(0, 2);
  const pBig = findWhere(s, (f) => f.w >= 49 && f.w <= 65 && f.h >= 55 && f.h <= 70);
  if (pBig) {
    const row = rowOf(s, pBig);
    const i = row.indexOf(pBig);
    const pre = row.slice(Math.max(0, i - 2), i).filter((f) => f.h >= 55 && f.w <= 45);
    punch = [...pre, pBig];
  }
  const punch3: Frame[] = [punch[punch.length - 1]];
  const punch2 = punch;
  const kick2: Frame[] = [punch[punch.length - 1]];

  // kick: extended-leg frame w 50-60, h 38-50
  let kick: Frame[] = punch;
  const kBig = findWhere(s, (f) => f.w >= 50 && f.w <= 60 && f.h >= 38 && f.h <= 50);
  if (kBig) {
    const row = rowOf(s, kBig);
    const i = row.indexOf(kBig);
    const pre = row.slice(Math.max(0, i - 1), i).filter((f) => f.h >= 35 && f.w <= 45);
    kick = [...pre, kBig];
  }

  // hurt: the shared [39x61, 41x60] reel pair (Tommy: 38x63 pair)
  const hurtSeq =
    findSeq(s, [
      [39, 61],
      [41, 60],
    ]) ||
    findSeq(
      s,
      [
        [38, 63],
        [38, 63],
      ],
      1,
    );
  const hurt = hurtSeq ? [hurtSeq[0]] : [idle[0]];

  // fall + down
  const fallF = findWhere(s, (f) => f.w >= 49 && f.w <= 65 && f.h >= 32 && f.h <= 53 && f !== kBig);
  const downF = findWhere(s, (f) => f.w >= 55 && f.h <= 33 && f.h >= 15);
  const down = downF ? [downF] : hurt;
  const fall = [fallF || hurt[0], down[0]];

  const victory = [morph[morph.length - 1]];

  return {
    idle,
    walk,
    jumpUp,
    jumpDown,
    punch,
    punch2,
    punch3,
    kick,
    kick2,
    hurt,
    fall,
    down,
    special: kick,
    victory,
    morph,
  };
}

/* ---------- putty patrol ---------- */

export function buildPutty(sheetKey = "putty"): AnimSet {
  const s = data[sheetKey];
  const idle = findSeq(s, [
    [41, 61],
    [41, 60],
    [45, 62],
  ]) || [s.rows[0][0]];

  let walk: Frame[] | null = null;
  for (const row of s.rows) {
    const run = row.filter((f) => f.h >= 62 && f.h <= 66 && f.w >= 38 && f.w <= 50);
    if (run.length >= 6) {
      walk = run.slice(0, 7);
      break;
    }
  }
  if (!walk) walk = idle;

  const a1 = findFrame(s, 47, 53, 2);
  const a2 = findFrame(s, 48, 55, 2);
  const a3 = findFrame(s, 112, 48, 5);
  const attack = a1 && a2 && a3 ? [a1, a2, a3] : idle;

  const h1 = findFrame(s, 47, 44, 2);
  const h2 = findFrame(s, 50, 54, 2);
  const hurt = h1 ? (h2 ? [h1, h2] : [h1]) : idle.slice(0, 1);

  const f1 = findFrame(s, 93, 55, 3);
  const d1 = findFrame(s, 76, 55, 3);
  const fall = f1 ? [f1, d1 || f1] : hurt;
  const down = [d1 || f1 || hurt[0]];

  return {
    idle,
    walk,
    jumpUp: idle.slice(0, 1),
    jumpDown: idle.slice(0, 1),
    punch: attack,
    punch2: attack,
    kick: attack,
    hurt,
    fall,
    down,
    special: attack,
    victory: idle.slice(0, 1),
    morph: idle.slice(0, 1),
    punch3: attack,
    kick2: attack,
  };
}

/* ---------- skelerena (fast skeletal hound, SNES boss mob) ---------- */

function buildSkelerena(): AnimSet {
  const s = data.skelerena;
  const r0 = s.rows[0] || [];
  const r1 = s.rows[1] || r0;
  const idle = r0.slice(0, 2);
  const walk = r1.slice(0, 4).filter((f) => f.h < 100);
  const lunge = findWhere(s, (f) => f.w >= 100 && f.h >= 70); // 111x80 bite
  const windup = findFrame(s, 77, 77, 3);
  const attack = lunge ? (windup ? [windup, lunge] : [lunge]) : idle;
  const hurtF = findFrame(s, 51, 80, 3);
  const hurt = hurtF ? [hurtF] : [idle[0]];
  const fallF = findFrame(s, 82, 79, 3);
  const fall = fallF ? [fallF] : hurt;
  // Skelerena: pick a wide/flat frame for the lying-down pose so it's distinct from the fall frame
  const downF = findWhere(s, (f) => f.h < 70 && f.w >= 70) || fallF;
  return {
    idle,
    walk: walk.length ? walk : idle,
    jumpUp: idle.slice(0, 1),
    jumpDown: idle.slice(0, 1),
    punch: attack,
    punch2: attack,
    kick: attack,
    hurt,
    fall,
    down: downF ? [downF] : fall,
    special: attack,
    victory: idle.slice(0, 1),
    morph: idle.slice(0, 1),
    punch3: attack,
    kick2: attack,
  };
}

/* ---------- ooze man (slow tanky ooze creature, Genesis) ---------- */

function buildOozeman(): AnimSet {
  const s = data.oozeman;
  const w1 = findFrame(s, 53, 68, 2);
  const w2 = findFrame(s, 54, 67, 2);
  const w3 = findFrame(s, 56, 65, 2);
  const idle = [w1, w2].filter(Boolean) as Frame[];
  const walk = [w1, w2, w3].filter(Boolean) as Frame[];
  const stretch = findWhere(s, (f) => f.w >= 105 && f.w <= 118 && f.h >= 55 && f.h <= 65); // 111x60
  const preF = findFrame(s, 51, 60, 2);
  const attack = stretch ? ((preF ? [preF, stretch] : [stretch]) as Frame[]) : idle;
  const hurtF = findFrame(s, 59, 69, 3);
  const hurt = hurtF ? [hurtF] : [idle[0]];
  const fallF = findFrame(s, 97, 65, 4);
  const downF = findFrame(s, 96, 38, 4);
  const fall = [fallF || hurt[0], downF || fallF || hurt[0]].filter(Boolean) as Frame[];
  return {
    idle: idle.length ? idle : [s.rows[0][0]],
    walk: walk.length ? walk : idle,
    jumpUp: idle.slice(0, 1),
    jumpDown: idle.slice(0, 1),
    punch: attack,
    punch2: attack,
    kick: attack,
    hurt,
    fall,
    down: [fall[fall.length - 1]],
    special: attack,
    victory: idle.slice(0, 1),
    morph: idle.slice(0, 1),
    punch3: attack,
    kick2: attack,
  };
}

const cache: Partial<Record<string, AnimSet>> = {};

export function buildAnims(key: CharKey): AnimSet {
  const k = "r_" + key;
  if (!cache[k]) cache[k] = buildGenesisRanger(key);
  return cache[k]!;
}

export function buildCivAnims(key: CharKey): AnimSet {
  const k = "c_" + key;
  if (!cache[k]) cache[k] = buildCivilian(key);
  return cache[k]!;
}

export function buildPuttyAnims(): AnimSet {
  if (!cache.putty) cache.putty = buildPutty();
  return cache.putty!;
}

export type EnemyKind = "putty" | "skelerena" | "oozeman";

export function buildEnemyAnims(kind: EnemyKind): AnimSet {
  if (!cache[kind]) {
    if (kind === "putty") cache[kind] = buildPutty();
    else if (kind === "oozeman") cache[kind] = buildOozeman();
    else if (data.skelerena && !data.skelerena.fallback) cache[kind] = buildSkelerena();
    else cache[kind] = buildPutty("skelerena"); // stand-in: recolored "Z-Putty" sheet
  }
  return cache[kind]!;
}

/** true when the Skelerena enemy is using the recolored Putty stand-in */
export function skelerenaIsFallback(): boolean {
  return !data.skelerena || !!data.skelerena.fallback;
}

export const RANGERS: {
  key: CharKey;
  name: string;
  human: string;
  color: string;
  glow: string;
  weapon: string;
  weaponId: WeaponId;
}[] = [
  {
    key: "red",
    name: "Ranger Vermelho",
    human: "Rocky",
    color: "#e02929",
    glow: "#ff6b6b",
    weapon: "Espada de Poder",
    weaponId: "red",
  },
  {
    key: "black",
    name: "Ranger Preto",
    human: "Adam",
    color: "#3a3a46",
    glow: "#9b9bb0",
    weapon: "Machado de Poder",
    weaponId: "black",
  },
  {
    key: "blue",
    name: "Ranger Azul",
    human: "Billy",
    color: "#2952e0",
    glow: "#6b8bff",
    weapon: "Lança de Poder",
    weaponId: "blue",
  },
  {
    key: "yellow",
    name: "Ranger Amarela",
    human: "Aisha",
    color: "#d8c020",
    glow: "#ffef6b",
    weapon: "Adagas de Poder",
    weaponId: "yellow",
  },
  {
    key: "pink",
    name: "Ranger Rosa",
    human: "Kimberly",
    color: "#e05490",
    glow: "#ff9bc4",
    weapon: "Arco de Poder",
    weaponId: "pink",
  },
  {
    key: "white",
    name: "Ranger Branco",
    human: "Tommy",
    color: "#d8d8e2",
    glow: "#ffffff",
    weapon: "Saba",
    weaponId: "white",
  },
];

export type WeaponId = "red" | "black" | "blue" | "yellow" | "pink" | "white";

export interface WeaponSpec {
  frames: Frame[];
  hitFrame: number;
  dmg: number;
  range: number;
  aoe: boolean;
  fx: WeaponFx;
}
export type WeaponFx =
  "sword_slash" | "axe_smash" | "lance_thrust" | "dagger_slash" | "arrow_rain" | "sabersword";

/* Each ranger's weapon swing, taken from its own sheet: wind-up → swing → recoil.
   (Power Sword, Power Axe, Power Lance, Power Daggers, Power Bow, Saba) */
export function getWeaponFrames(key: CharKey): Frame[] {
  return weaponRow(data[RANGER_SHEET[key]]);
}

export const WEAPON_SPECS: Record<WeaponId, Omit<WeaponSpec, "frames">> = {
  red: { hitFrame: 1, dmg: 28, range: 120, aoe: true, fx: "sword_slash" },
  black: { hitFrame: 1, dmg: 38, range: 100, aoe: false, fx: "axe_smash" },
  blue: { hitFrame: 1, dmg: 32, range: 200, aoe: false, fx: "lance_thrust" },
  yellow: { hitFrame: 1, dmg: 22, range: 110, aoe: true, fx: "dagger_slash" },
  pink: { hitFrame: 1, dmg: 34, range: 180, aoe: false, fx: "arrow_rain" },
  white: { hitFrame: 1, dmg: 40, range: 160, aoe: true, fx: "sabersword" },
};
